### ISSUE TITLE
CS2103 website build fails due to missing bootstrap-icons.css

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2538]
v5.5.0

[CS2103 website](https://github.com/nus-cs2103/website-base) doesn't work anymore after upgrading to v5.5.0
The error I get when running `markbind serve -o` is the below:

```
warn:  message=Cannot find module 'bootstrap-icons/font/bootstrap-icons.css'
...
```

**Comment by kaixin-hc** [comment]
Seems it was added to the wrong package lock and we missed it. See similar PR:  #1681 and look at the files changed in the PR I just made: https://github.com/MarkBind/markbind/pull/2539

Locally, it runs fine - I assume because of hoisting? It also works for the MarkBind website for some reason - and most CI check passes.

https://www.jonathancreamer.com/inside-the-pain-of-monorepos-and-hoisting/ talks about some of the edge cases that can come up in a monorepo. I haven't quite worked out how this one happened where it throws a fit on some sites but not others, but its likely for a similar reason.

Tagging @yiwen101 because he might be curious about this.

**Comment by yiwen101** [comment]
Sorry for causing this issue due to my neglect.
@kaixin-hc Thank you so much for your quick fix and investigation

**Comment by kaixin-hc** [comment]
@yiwen101 on't worry! None of us caught it either in review, such things happen

**Comment by damithc** [comment]
> @yiwen101 on't worry! None of us caught it either in review, such things happen

Yup. these things happen. While we should try to minimize, it's not always feasible to do so. So, what matters is how quickly we can respond to such cases when discovered.

On a related note, it might be a good idea to smoke test on the CS2103 website before we do a release, or before merging a major feature. If it can survive the CS2103 website, chances are it can survive anything :-D

**Comment by ckcherry23** [comment]
Seems like the CS3282 website deployment is still having some issues with the new version due to an undefined "path" argument. 
```
uncaughtException: The "path" argument must be of type string. Received undefined 
```
<img width="1512" alt="Screenshot 2024-05-01 at 2 08 07 AM" src="https://github.com/MarkBind/markbind/assets/68203159/da0659bd-a8fa-447c-a5ab-d6d97ee8836b">

CI run: https://github.com/nus-cs3281/2024/actions/runs/8899519872/job/24439067023

On a related note, it would be nice if the CI status fails when the deployment has an error, for better DX.

**Comment by yiwen101** [comment]
@ckcherry23 
Thank you for raising this issue up, and the suggestion on better CI.
A quick investigation shows that this problem is first observable after this depend-bot update [pr](https://github.com/MarkBind/markbind/pull/2532).

**Comment by yiwen101** [comment]
Strangely, I still see the error even if I do this; I have no idea where the argument "path" comes from.
<img width="545" alt="Screenshot 2024-05-01 at 03 35 28" src="https://github.com/MarkBind/markbind/assets/121547057/10ed3b7c-f2fd-4aad-9950-ff1688cceec7">
<img width="677" alt="Screenshot 2024-05-01 at 03 35 12" src="https://github.com/MarkBind/markbind/assets/121547057/5749ab56-472d-4bb6-8a02-5901749ae91b">

I wonder if there is a better fix than reverting the version update.

**Comment by tlylt** [comment]
On a brief look, is the error because of Vue hydration issue that breaks the page? Maybe @yiwen101 can confirm
![image](https://github.com/MarkBind/markbind/assets/41845017/7e5c205e-6b19-41dd-9277-36669e42dacc)

**Comment by kaixin-hc** [comment]
Interesting... @EltonGohJH has been looking into this, we think it might be the 3.0.0 update of gh-pages that moves the cache directory default location and also allows you to manually specify a cache directory. It might be that it is required

**Comment by yiwen101** [comment]
> On a brief look, is the error because of Vue hydration issue that breaks the page? Maybe @yiwen101 can confirm
> ![image](https://private-user-images.githubusercontent.com/41845017/327035061-7e5c205e-6b19-41dd-9277-36669e42dacc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MzkzMzgsIm5iZiI6MTcxNDUzOTAzOCwicGF0aCI6Ii80MTg0NTAxNy8zMjcwMzUwNjEtN2U1YzIwNWUtNmIxOS00MWRkLTkyNzctMzY2NjllNDJkYWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA0NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZDMwYWVmZGNiZmM5ZTc4ODVkZTVmMTM3ODNlYzI2M2Y4MjJhMjc1MjRmMzYyMjlmYmU3OTdiN2NlY2YwMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80z8z1j2nl1O4SX31Eo3pFqSlOpKVPYcq3CysCtOfNk)

I do not think the missing tbody issue is related to the "path is undefined" problem we are facing, although there is indeed table without tbody spotted here.
<img width="1108" alt="Screenshot 2024-05-01 at 12 52 06" src="https://github.com/MarkBind/markbind/assets/121547057/7871854c-4620-4b1f-9cf3-e540ce013677">

But it does not seem to be causing hydration in the current deployed site.

Interestingly, I also noticed that when I checkout to ba0b92d28, this code that has caused hydration in the past also does not cause hydration locally on my device now. 
<img width="1267" alt="Screenshot 2024-05-01 at 12 52 48" src="https://github.com/MarkBind/markbind/assets/121547057/478f000f-99a5-411e-9fe8-5394f25b2e98">

**Comment by EltonGohJH** [comment]
https://github.com/EltonGohJH/2024/commit/c6d21912e250b410294effe42f2faf190f9139c6

The problem seems that when running the github action it fails to locate the .cache folder. When I set it manually in my fork it works. 

So, I created a PR to set it to a location if it is github action.

**Comment by kaixin-hc** [comment]
> Interestingly, I also noticed that when I checkout to ba0b92d28, this code that has caused hydration in the past also does not cause hydration locally on my device now.

Very interesting! Hmm... if its now so robust even that doesn't throw an error, we can consider if we need to remove it later. But better safe than sorry. Anyway, JIC I've pushed the proper vue hydration to the 2024 master, doesn't hurt anything
